name: Docker Image CI

on:
  workflow_dispatch:
  push:
    paths:
      - src/**
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Set up JDK 17 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64

    - id: project
      name: Extract Maven project version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)

    - uses: docker/login-action@v3
      name: Login to Docker Hub
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v4
    - name: Build the Docker image and push to the docker registery
      run: |
        docker build . \ 
            --tag moalhaddar/docx-to-pdf:latest \
            --tag moalhaddar/docx-to-pdf:${{ steps.project.outputs.version }}-${{github.run_attempt}}
        docker push moalhaddar/docx-to-pdf:latest
      
