name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: docker/login-action@v3
      name: Login to Docker Hub
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - uses: actions/checkout@v4
    - name: Build the Docker image and push to the docker registery
      run: |
        docker build . --tag moalhaddar/docx-to-pdf:latest
        docker push moalhaddar/docx-to-pdf:latest
      
